#############################################################################
# Makefile for building: Little\ Writer
# Generated by qmake (2.01a) (Qt 4.8.7) on: dom lug 17 01:54:57 2016
# Project:  littlewriter.pro
# Template: app
# Command: /boot/system/bin/x86/qmake -o Makefile littlewriter.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I../../../system/data/Qt/mkspecs/haiku-g++ -I. -I../../../system/develop/headers/x86/QtCore -I../../../system/develop/headers/x86/QtGui -I../../../system/develop/headers/x86 -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/packages/libqt4_x86-4.8.7-5/.self/lib/x86
LIBS          = $(SUBLIBS)  -L/packages/libqt4_x86-4.8.7-5/.self/lib/x86 -lroot -lQtGui -lQtCore 
AR            = ar cqs
RANLIB        = 
QMAKE         = /boot/system/bin/x86/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = textedit.cpp \
		main.cpp moc_textedit.cpp \
		qrc_textedit.cpp
OBJECTS       = textedit.o \
		main.o \
		moc_textedit.o \
		qrc_textedit.o
DIST          = ../../../system/data/Qt/mkspecs/common/gcc-base.conf \
		../../../system/data/Qt/mkspecs/common/gcc-base-unix.conf \
		../../../system/data/Qt/mkspecs/common/g++-base.conf \
		../../../system/data/Qt/mkspecs/common/g++-unix.conf \
		../../../system/data/Qt/mkspecs/common/unix.conf \
		../../../system/data/Qt/mkspecs/qconfig.pri \
		../../../system/data/Qt/mkspecs/modules/qt_webkit_version.pri \
		../../../system/data/Qt/mkspecs/features/qt_functions.prf \
		../../../system/data/Qt/mkspecs/features/qt_config.prf \
		../../../system/data/Qt/mkspecs/features/exclusive_builds.prf \
		../../../system/data/Qt/mkspecs/features/default_pre.prf \
		../../../system/data/Qt/mkspecs/features/release.prf \
		../../../system/data/Qt/mkspecs/features/default_post.prf \
		../../../system/data/Qt/mkspecs/features/warn_on.prf \
		../../../system/data/Qt/mkspecs/features/qt.prf \
		../../../system/data/Qt/mkspecs/features/unix/thread.prf \
		../../../system/data/Qt/mkspecs/features/moc.prf \
		../../../system/data/Qt/mkspecs/features/shared.prf \
		../../../system/data/Qt/mkspecs/features/resources.prf \
		../../../system/data/Qt/mkspecs/features/uic.prf \
		../../../system/data/Qt/mkspecs/features/yacc.prf \
		../../../system/data/Qt/mkspecs/features/lex.prf \
		../../../system/data/Qt/mkspecs/features/include_source_dir.prf \
		littlewriter.pro
QMAKE_TARGET  = Little Writer
DESTDIR       = 
TARGET        = Little\ Writer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: littlewriter.pro  ../../../system/data/Qt/mkspecs/haiku-g++/qmake.conf ../../../system/data/Qt/mkspecs/common/gcc-base.conf \
		../../../system/data/Qt/mkspecs/common/gcc-base-unix.conf \
		../../../system/data/Qt/mkspecs/common/g++-base.conf \
		../../../system/data/Qt/mkspecs/common/g++-unix.conf \
		../../../system/data/Qt/mkspecs/common/unix.conf \
		../../../system/data/Qt/mkspecs/qconfig.pri \
		../../../system/data/Qt/mkspecs/modules/qt_webkit_version.pri \
		../../../system/data/Qt/mkspecs/features/qt_functions.prf \
		../../../system/data/Qt/mkspecs/features/qt_config.prf \
		../../../system/data/Qt/mkspecs/features/exclusive_builds.prf \
		../../../system/data/Qt/mkspecs/features/default_pre.prf \
		../../../system/data/Qt/mkspecs/features/release.prf \
		../../../system/data/Qt/mkspecs/features/default_post.prf \
		../../../system/data/Qt/mkspecs/features/warn_on.prf \
		../../../system/data/Qt/mkspecs/features/qt.prf \
		../../../system/data/Qt/mkspecs/features/unix/thread.prf \
		../../../system/data/Qt/mkspecs/features/moc.prf \
		../../../system/data/Qt/mkspecs/features/shared.prf \
		../../../system/data/Qt/mkspecs/features/resources.prf \
		../../../system/data/Qt/mkspecs/features/uic.prf \
		../../../system/data/Qt/mkspecs/features/yacc.prf \
		../../../system/data/Qt/mkspecs/features/lex.prf \
		../../../system/data/Qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile littlewriter.pro
../../../system/data/Qt/mkspecs/common/gcc-base.conf:
../../../system/data/Qt/mkspecs/common/gcc-base-unix.conf:
../../../system/data/Qt/mkspecs/common/g++-base.conf:
../../../system/data/Qt/mkspecs/common/g++-unix.conf:
../../../system/data/Qt/mkspecs/common/unix.conf:
../../../system/data/Qt/mkspecs/qconfig.pri:
../../../system/data/Qt/mkspecs/modules/qt_webkit_version.pri:
../../../system/data/Qt/mkspecs/features/qt_functions.prf:
../../../system/data/Qt/mkspecs/features/qt_config.prf:
../../../system/data/Qt/mkspecs/features/exclusive_builds.prf:
../../../system/data/Qt/mkspecs/features/default_pre.prf:
../../../system/data/Qt/mkspecs/features/release.prf:
../../../system/data/Qt/mkspecs/features/default_post.prf:
../../../system/data/Qt/mkspecs/features/warn_on.prf:
../../../system/data/Qt/mkspecs/features/qt.prf:
../../../system/data/Qt/mkspecs/features/unix/thread.prf:
../../../system/data/Qt/mkspecs/features/moc.prf:
../../../system/data/Qt/mkspecs/features/shared.prf:
../../../system/data/Qt/mkspecs/features/resources.prf:
../../../system/data/Qt/mkspecs/features/uic.prf:
../../../system/data/Qt/mkspecs/features/yacc.prf:
../../../system/data/Qt/mkspecs/features/lex.prf:
../../../system/data/Qt/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile littlewriter.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Little1.0.0 || $(MKDIR) .tmp/Little1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Little1.0.0/ && $(COPY_FILE) --parents textedit.h .tmp/Little1.0.0/ && $(COPY_FILE) --parents textedit.qrc .tmp/Little1.0.0/ && $(COPY_FILE) --parents textedit.cpp main.cpp .tmp/Little1.0.0/ && (cd `dirname .tmp/Little1.0.0` && $(TAR) Little1.0.0.tar Little1.0.0 && $(COMPRESS) Little1.0.0.tar) && $(MOVE) `dirname .tmp/Little1.0.0`/Little1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Little1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_textedit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_textedit.cpp
moc_textedit.cpp: textedit.h
	/packages/libqt4_x86-4.8.7-5/.self/bin/x86/moc $(DEFINES) $(INCPATH) textedit.h -o moc_textedit.cpp

compiler_rcc_make_all: qrc_textedit.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_textedit.cpp
qrc_textedit.cpp: textedit.qrc \
		images/haiku/editredo.png \
		images/haiku/exportpdf.png \
		images/haiku/fileprint.png \
		images/haiku/editcopy.png \
		images/haiku/textright.png \
		images/haiku/editundo.png \
		images/haiku/textunder.png \
		images/haiku/filesave.png \
		images/haiku/texthighlight.png \
		images/haiku/bgfill.png \
		images/haiku/editcut.png \
		images/haiku/fileopen.png \
		images/haiku/WordWriter.png \
		images/haiku/textcolor.png \
		images/haiku/textcenter.png \
		images/haiku/zoomout.png \
		images/haiku/image.png \
		images/haiku/textitalic.png \
		images/haiku/filenew.png \
		images/haiku/textleft.png \
		images/haiku/textbold.png \
		images/haiku/editpaste.png \
		images/haiku/zoomin.png \
		images/haiku/textjustify.png
	/packages/libqt4_x86-4.8.7-5/.self/bin/x86/rcc -name textedit textedit.qrc -o qrc_textedit.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

textedit.o: textedit.cpp textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textedit.o textedit.cpp

main.o: main.cpp textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_textedit.o: moc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textedit.o moc_textedit.cpp

qrc_textedit.o: qrc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_textedit.o qrc_textedit.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/ || $(MKDIR) $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/ || $(MKDIR) $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/ 
	-$(INSTALL_FILE) /boot/home/develop/textedit/textedit.cpp $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/
	-$(INSTALL_FILE) /boot/home/develop/textedit/main.cpp $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/
	-$(INSTALL_FILE) /boot/home/develop/textedit/textedit.h $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/
	-$(INSTALL_FILE) /boot/home/develop/textedit/textedit.qrc $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/
	-$(INSTALL_FILE) /boot/home/develop/textedit/littlewriter.pro $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/
	-$(INSTALL_FILE) /boot/home/develop/textedit/example.bak.html $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/
	-$(INSTALL_FILE) /boot/home/develop/textedit/example.html $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/
	-$(INSTALL_DIR) /boot/home/develop/textedit/images $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/textedit.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/textedit.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/textedit.qrc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/littlewriter.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/example.bak.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/example.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/images
	-$(DEL_DIR) $(INSTALL_ROOT)/packages/libqt4_x86-4.8.7-5/.self/data/Qt/demos/textedit/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

